/// <reference types="next" />
/// <reference types="next/image-types/global" />

<<<<<<< HEAD
// This file is generated by Next.js; keep it unedited.
=======
// This file is generated by Next.js and should not be edited.
>>>>>>> 5d2a9f64c85a66b65b6ef4e73a2d6ae7b75a4ee0
